name: japanese_word_tokenizer
description: A lightweight Japanese word tokenizer library for Dart and Flutter based on wakachigaki
version: 0.0.3
repository: https://github.com/Adora-Inc/japanese_word_tokenizer
homepage: https://github.com/Adora-Inc/japanese_word_tokenizer

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:

dev_dependencies:
  test: ^1.25.8

